### PR TITLE
Hopefully correct

### PR DESCRIPTION
**Pull request by SidneyLovelady**

### CODE REVIEW

**Comment by mtseng15** [comment]
@SidneyLovelady No files were changed so nothing was resolved. You need to merge `new_feature` into master.

**Comment by SidneyLovelady** [comment]
I resolved the error by keeping the original line 9. Should I have changed it to the one in the new_feature branch? If so, I had to modify the new_feature cpp file such that it would even recognize that the master and new_feature were different even though there were two completely different line 9's.

**Comment by mtseng15** [comment]
Nope, I think it's a basic git issue. Look at this commit :https://github.com/UAH-IC-Design-Team/hw01-q2/commit/1fd93b9ad673f748481d1e57f84978b079df5205
There's no files in it. So it looks like you didn't index any files before committing.

**Comment by SidneyLovelady** [comment]
@mtseng15 I think I have it fixed now. Had to do some tomfoolery to get things reverted and made a bit of a mess in the process, but hopefully the repo is correct now.

**Comment by mtseng15** [comment]
@SidneyLovelady Solid! That works. I would recommend restarting and taking another clean crack at it for practice. Ideally, it should take less than 3min and your commit history would look something like below. 


Screen Shot 2023-01-23 at 1 41 02 AM

I'm closing this without merging for others to work on :)

**Pull request closed without merging**
